### ISSUE TITLE
案山子機能

### ISSUE THREAD

**Issue by thinca** [supermomonga/akechi.rukkit#15]
### 概要
案山子を設置することで、案山子の周囲のある程度の範囲のチャンクをアンロードさせないようにできる。
農業や酪農で効果を発揮する。

#### 案山子オブジェクトの定義
頭部分にはカボチャや Mob の頭などの案が上がっている。
(誰かもうちょいまとめてもらえると助かる)

#### 範囲の定義
どのくらいの範囲に影響するか。
1チャンク(16x16)は小さすぎる気がするので、もう1周り大きくした9チャンクくらい?
意見募集

#### 使用制限
みんなが際限なく設置すると、アンロードされないチャンクが増え、結果、サーバがかなり重くなってしまうことが懸念される。よって、使用制限が必要。
例えば1人1つまで、など。ただ、共有の案山子が欲しいという意見もあり、更に意見募集。

**Comment by ujihisa** [comment]
ばっちり動作してると聞いて
