### ISSUE TITLE
momonga鯖への移住

### ISSUE THREAD

**Issue by supermomonga** [supermomonga/akechi.rukkit#5]
http://lingr.com/room/mcujm/archives/2014/11/24#message-20693093

![2014-11-25 4 40 13](https://cloud.githubusercontent.com/assets/377137/5171687/3c89daf2-745d-11e4-94d5-b1e239531d4b.png)

![2014-11-25 4 40 34](https://cloud.githubusercontent.com/assets/377137/5171691/4482e9d8-745d-11e4-8c79-77be1d73a7af.png)

---

というわけでみなさん切断されまくるので試しに日本で鯖立ててみました

`rukkit.com:25565` です

というわけで各位試してもらえると嬉しいです。

@ujihisa 
@thinca 
@mtwtkman 
@aomoriringo 
@raa0121 
@kamichidu 
@deris 
- [ ] test

**Comment by ujihisa** [comment]
時代はももんが鯖

またminecraftする機運が高まってきたぞ

**Comment by supermomonga** [comment]
お

**Comment by ujihisa** [comment]
やっていこうぜ
