### ISSUE TITLE
データのホストもコンテナで行いたい

### ISSUE THREAD

**Issue by supermomonga** [supermomonga/akechi.rukkit#7]
現状、地形データやrukkit用`config.yml`、dynmapの地形画像データなどはホスト側に保存していますが、[Data-only Container Pattern](http://qiita.com/mopemope/items/b05ff7f603a5ad74bf55#2-2)を使って、データ永続化用のdockerコンテナを専用に作ってデータのポータビリティも上げたい。

実現すればデータ含めて別のサーバーに一瞬で移せて便利

**Comment by ujihisa** [comment]
時代はdocker-compose
